accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import SignupView

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignupView.as_view(), name="signup")
]

book/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index_view, name="index"),
    path("book/", views.ListBookView.as_view(), name="list-book"),
    path("book/<int:pk>/detail/", views.DetailBookView.as_view(), name="detail-book"),
    path("book/create/", views.CreateBookView.as_view(), name="create-book"),
    path("book/<int:pk>/delete/", views.DeleteBookView.as_view(), name="delete-book"),
    path("book/<int:pk>/update/", views.UpdateBookView.as_view(), name="update-book"),
    path("book/<int:book_id>/review/",
         views.CreateReviewView.as_view(), name="review"),
    # path("logout/", views.logout_view, name="logout"),
]

bookproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("book.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATICFILES_DIRS)
# 上記の記載方法は本番環境では使わない

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

accounts/models.py
from django.db import models

# Create your models here.

book/models.py
from django.db import models
from .consts import MAX_RATE
# Create your models here.


# class SampleModel(models.Model):
#     title = models.CharField(max_length=100)
#     number = models.IntegerField()
CATEGORY = (("web", "web"), ("sumaho", "スマホアプリ"),
            ("xr", "XR"), ("game", "ゲーム"), ("other", "その他"))

RATE_CHOICES = [(x, str(x)) for x in range(0, MAX_RATE+1)]


class Book(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    thumbnail = models.ImageField(null=True, blank=True)
    category = models.CharField(
        max_length=100,
        choices=CATEGORY
    )
    url = models.URLField(null=True, blank=True)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title  # title = models.CharField(max_length=100)


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    rate = models.IntegerField(choices=RATE_CHOICES)
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)

book/forms.py
""" from django import forms


class CreateBookForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'text', 'thumbnail', 'category', 'user')
 """

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import SignupForm
# Create your views here.


class SignupView(CreateView):
    model = User
    form_class = SignupForm  # form_classが定義されていないと、model=の中で定義されたモデルに基づいてModelFormが自動作成される
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("index")

book/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import Book, Review
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Avg
from django.core.paginator import Paginator
from .consts import ITEM_PER_PAGE
from django.views import generic
# from .forms import CreateBookForm
import os
# Create your views here.


class ListBookView(LoginRequiredMixin, ListView):
    template_name = "book/book_list.html"
    # htmlファイルで↓のモデルの中身が使いまわされる
    model = Book
    paginate_by = ITEM_PER_PAGE


class DetailBookView(LoginRequiredMixin, DetailView):
    template_name = "book/book_detail.html"
    model = Book

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        obj.views += 1
        obj.save()

        return obj


class CreateBookView(LoginRequiredMixin, CreateView):
    template_name = "book/book_create.html"
    model = Book
    fields = {"title", "text", "category", "thumbnail", "url"}
    success_url = reverse_lazy("index")
    # form_class = CreateBookForm

    def form_valid(self, form):
        # ユーザー情報の追加をする関数
        form.instance.user = self.request.user

        """ save_path = str("media/"+self.request.FILES['picture'])
        up_data = self.request.FILES['picture']
        with open(save_path, 'wb+') as i:
            for chunk in up_data.chunks():
                i.write(chunk)
        with PIL.Image.open(save_path) as image:
            os.remove(save_path)

            # 画像の縦横比をそのままに480×640以下にリサイズ
            resized_height = 640 / int(image.size[0]) * image.size[1]
            resized_image = image.resize((640, int(resized_height)))
            if resized_height > 480:
                resized_width = 480 / int(image.size[1]) * image.size[0]
                resized_image = resized_image.resize((int(resized_width), 480))

            image_io = io.BytesIO()
            resized_image.save(image_io, format="JPEG")
            image_file = InMemoryUploadedFile(image_io, field_name=None, name=save_path,
                                              content_type="image/jpeg", size=image_io.getbuffer().nbytes,
                                              charset=None)

        post = form.save(commit=False)
        post.picture = image_file
        post.save() """

        return super().form_valid(form)


class DeleteBookView(LoginRequiredMixin, DeleteView):
    template_name = "book/book_delete.html"
    model = Book
    success_url = reverse_lazy("index")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if obj.user != self.request.user:
            raise PermissionDenied

        return obj


class UpdateBookView(LoginRequiredMixin, UpdateView):
    template_name = "book/book_update.html"
    model = Book
    fields = {"title", "text", "category", "thumbnail", "url"}
    # success_url = reverse_lazy("index")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if obj.user != self.request.user:
            raise PermissionDenied

        return obj

    def get_success_url(self):
        return reverse("detail-book", kwargs={"pk": self.object.id})


class CreateReviewView(LoginRequiredMixin, CreateView):
    template_name = "book/review_form.html"
    model = Review
    fields = {"book", "title", "text", "rate"}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["book"] = Book.objects.get(pk=self.kwargs["book_id"])
        # print(context)
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("detail-book", kwargs={"pk": self.object.book.id})


def index_view(request):
    # print("index_view is called")
    object_list = Book.objects.order_by("-id")
    # templatename,model
    ranking_list = Book.objects.annotate(
        avg_rating=Avg("review__rate")).order_by("-avg_rating")

    paginator = Paginator(ranking_list, ITEM_PER_PAGE)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.page(page_number)

    # query = request.GET.get('number')
    # print(query)
    # print(ranking_list[0].avg_rating)
    return render(request, "book/index.html", {"object_list": object_list, "ranking_list": ranking_list, "page_obj": page_obj},)


# def logout_view(request):
#     logout(request)
#     return redirect("index")  # success_url

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}アカウント作成{% endblock %}
{% block h1 %}アカウント作成{% endblock %}

{% block content %}
<form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <input type="text" name="username" class="form-control my-4" placeholder="ユーザー ID">
    <input type="password" name="password1" class="form-control mt-4" placeholder="パスワード">
    <input type="password" name="password2" class="form-control mt-4" placeholder="パスワード(確認用)">
    <small class="mb-2 d-block text-start">パスワードは半角英字、数字を組み合わせて8文字以上で設定して下さい。</small>
    {% if form.errors %}
    <span class="mb-2 small text-danger d-block text-start">入力されたユーザーIDまたはパスワードが利用できません。</span>
    {% endif %}
    <button type="submit" class="btn btn-success m-2">アカウント作成</button>
</form>
{% endblock content%}

book/templates/book/book_create.html
{% extends "base.html" %}

{% block title %}プロダクト作成{% endblock %}
{% block h1 %}書籍作成{% endblock %}


{% block content %}
<form method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="作成する">
</form>
{% endblock content %}

book/templates/book/book_delete.html
{% extends "base.html" %}

{% block title %}プロダクト削除{% endblock %}
{% block h1 %}書籍削除{% endblock %}


{% block content %}
<form method="POST">
    {% csrf_token %}
    <button type="submit">{{ object.title }}を削除する</button>
</form>
{% endblock content %}

book/templates/book/book_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{object.title}}{% endblock %}
{% block h1 %}{{object.title}}{% endblock %}

{% block content %}
<!-- Bootstrapのグリッドシステム-->
<br>
<div class="album py-5 bg-light">

    <div class="container">
        <!-- 行を配置 -->
        <div class="row">
            <!-- 列の左右に余白offset-3を入れる-->
            <div class="col offset-0">
                <!-- タイトル -->
                <!-- <h2>{{object.title}}</h2> -->
                <h2 class="card-title">{{object.title}}</h2>
                <h6>
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-eye-check" width="20"
                        height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                        stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path>
                        <path
                            d="M11.143 17.961c-3.221 -.295 -5.936 -2.281 -8.143 -5.961c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6c-.222 .37 -.449 .722 -.68 1.057">
                        </path>
                        <path d="M15 19l2 2l4 -4"></path>
                    </svg>
                    {{object.views}}回 ・
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="20"
                        height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                        stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
                        <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
                        <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
                    </svg>
                    {{object.user}}
                </h6>
                <div class="px-2">
                    <span>
                        {% if object.url %}
                        <p>{{object.url|urlize}}</p>
                        {% endif %}
                    </span>
                    <!-- コメント -->
                    <p>{{object.text}}</p>

                </div>
                <br>
                <!-- 1枚目の写真 -->
                {% if object.thumbnail %}
                <p><img src="{{ object.thumbnail.url }}" height="500"></img></p>
                {% else %}
                <p><img src="{% static 'book/noimage.png' %}" height="500"></img></p>
                {% endif %}


                <a href="{% url 'review' object.pk %}" class="btn btn-primary">レビューする</a>
                <a href="{% url 'update-book' object.pk %}" class="btn btn-primary">編集する</a>
                <a href="{% url 'delete-book' object.pk %}" class="btn btn-primary">削除する</a>
                <span class="mb-2 small text-danger d-block text-start">編集と削除は投稿者の方のみご利用頂けます。</span>


                <br>
                {% if object.review_set.all %}
                <div class="border p-4 mb-2">
                    {% for review in object.review_set.all %}
                    <div>
                        <h3 class="h4">{{review.title}}</h3>
                        <div class="px-2">
                            <span>(投稿ユーザー: {{review.user.username}})</span>
                            <h6>評価:{{review.rate}}点</h6>
                            <p>{{review.text}}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                {% else %}
                <div class="border p-4 mb-2">
                    <span class="mb-2 small d-block text-start">まだコメントはありません。</span>
                </div>


                {% endif %}


            </div>
        </div>
    </div>
    {% endblock content %}

book/templates/book/book_list.html
{% extends "base.html" %}

{% block title %}書籍一覧{% endblock %}
{% block h1 %}書籍一覧{% endblock %}

{% block content %}
{% for item in object_list %}
<div class="p-4 m-4 bg-light border border-success rounded">
    <h2 class="text-success">{{item.title}}</h2>
    <h6>{{item.category}}</h6>
    <div class="mt-3">
        <a href="{% url 'detail-book' item.pk %}">詳細へ</a>
    </div>
    <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
</div>
{% endfor %}
{% include "book/components/pagination.html" %}
{% endblock content %}

book/templates/book/book_update.html
{% extends "base.html" %}

{% block title %}プロダクト修正{% endblock %}
{% block h1 %}書籍修正{% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="修正する">
</form>
{% endblock content %}

book/templates/book/components/pagination.html
{% if page_obj.has_other_pages %}
<ul class="list-unstyled m-0 d-flex justify-content-between">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">&lt;&lt;前へ</a></li>
    {% else %}
    <li class="text-muted">&lt;&lt;前へ</li>
    {% endif %}
    {% if page_obj.has_next %}
    <li>
        <a href="?page{{ page_obj.next_page_number }}">次へ&gt;&gt;</a>
    </li>
    {% else %}
    <li class="text-muted">次へ&gt;&gt;</li>
    {% endif %}
</ul>
{% endif %}

book/templates/book/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}ホーム{% endblock %}
{% block h1 %}本だなアプリ{% endblock %}

{% block content %}
<!-- タイトルとナビゲーションボタン -->
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <!-- タイトルと本文 -->
            <h1 class="fw-light">Product Gallery</h1>
            <p class="lead text-muted">
                プロダクトの投稿サイトです。サムネイルも付けてくださいね！
            </p>
            <p>
                <!-- ナビゲーションボタン -->
                {% if request.user.is_authenticated %}
                <!-- ログイン中のボタン -->
                <a href="{% url 'create-book' %}" class="btn btn-primary my-2">プロダクト登録</a>
                <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
                {% else %}
                <!-- ログイン状態ではない場合のボタン -->
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">サインアップ</a>
                <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">ログイン</a>
                {% endif %}
            </p>
        </div>
    </div>
</section>

<div class="album py-5 bg-light">
    <!-- Bootstrapのグリッドシステムを適用 -->
    <div class="container">
        <!-- 行要素を配置 -->
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <!-- レコードが格納されたobject_listから
             レコードを1行ずつrecordに取り出す-->
            {% for item in object_list %}
            <!-- 列要素を配置 -->
            <div class="col">
                <div class="card shadow-sm">
                    <!-- svgタグをimgに変更
                 src属性を追加して1枚目のイメージのURLを設定 -->
                    {% if item.thumbnail %}
                    <img src="{{ item.thumbnail.url }}" class="bd-placeholder-img card-img-top" width="100%"
                        height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                        preserveAspectRatio="xMidYMid slice" focusable="false">


                    {% else %}
                    <img src="{% static 'book/noimage.png' %}" class="bd-placeholder-img card-img-top" width="100%"
                        height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                        preserveAspectRatio="xMidYMid slice" focusable="false">


                    {% endif %}
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#55595c" />


                    <!-- タイトルとボタンを出力するブロック -->
                    <div class="card-body">
                        <p class="card-text">
                            <!-- titleフィールドを出力 -->
                            {{item.title}}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <!-- 詳細ページを表示するボタン -->
                                <button type="button" class="btn btn-sm btn-outline-secondary"
                                    onclick="location.href='{% url 'detail-book' item.pk %}'">
                                    View</button>
                                <!-- カテゴリを表示するボタン -->

                            </div>
                            <!-- 投稿したユーザー名を出力-->
                            <small class="text-muted">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-eye-check"
                                    width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                                    fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path>
                                    <path
                                        d="M11.143 17.961c-3.221 -.295 -5.936 -2.281 -8.143 -5.961c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6c-.222 .37 -.449 .722 -.68 1.057">
                                    </path>
                                    <path d="M15 19l2 2l4 -4"></path>
                                </svg>
                                {{item.views}}回 ・
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle"
                                    width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                                    fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
                                    <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
                                    <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
                                </svg>
                                {{item.user}}
                            </small>


                        </div>
                    </div>
                </div>
                <!-- 列要素ここまで -->
            </div>
            <!-- forブロック終了 -->
            {% endfor %}
            <!-- 行要素ここまで -->
        </div>
        <!-- グリッドシステムここまで -->
    </div>
</div>







{% endblock content %}

book/templates/book/review_form.html
{% extends "base.html" %}

{% block title %}レビュー投稿{% endblock %}
{% block h1 %}レビュー投稿{% endblock %}

{% block content %}
<form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <label>対象プロダクト</label>
    <input class="form-control" value="{{book.title}}" readonly>
    <label>タイトル</label>
    <input class="form-control" name="title">
    <label>本文</label>
    <textarea class="form-control" name="text" rows="3"></textarea>
    <label>星の数</label>
    <select class="form-control" name="rate">
        <option value="0">0</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
    </select>
    <input type="hidden" name="book" value="{{book.id}}">
    <button type="submit" class="btn btn-success mt-4">投稿する</button>
</form>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">


    <title>{% block title %}{% endblock title %}| Product Gallery</title>
    <!-- staticでfavicon.icoのURLを生成する -->
    <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>

<body>
    <!-- ページのヘッダー-->
    <header>
        <!-- ナビゲーションバーのヘッダー-->
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        <!-- ヘッダーのタイトルと本文-->
                        <h4 class="text-white">お気に入りを見つけよう！</h4>
                        <p class="text-muted">
                            誰でも参加できるプロダクト投稿サイトです。
                            <br>
                            自分で制作したプロダクトなら何でもオッケー！
                            コメントも付けてみてください！
                        </p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Menu</h4>
                        <ul class="list-unstyled">
                            <!-- ナビゲーションメニュー-->
                            {% if request.user.is_authenticated %}
                            <!-- ログイン中のメニュー-->
                            <li><a href="{% url 'index' %}" class="text-white">プロダクト一覧</a></li>
                            <li><a href="{% url 'create-book' %}" class="text-white">プロダクト登録</a></li>
                            <li><a href="{% url 'accounts:logout' %}" class="text-white">ログアウト</a></li>
                            {% else %}
                            <!-- ログイン状態ではない場合のメニュー-->
                            <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
                            <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- ナビゲーションバー-->
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container">
                <!-- トップページへのリンク-->
                <a href="{% url 'index' %}" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                        viewBox="0 0 24 24">
                        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                        <circle cx="12" cy="13" r="4" />
                    </svg>
                    <!-- リンクテキスト-->
                    <strong>
                        Product Gallery
                        <small class="text-muted">
                            &nbsp;&nbsp;by yotech&gt;&gt;
                        </small>
                    </strong>
                </a>
                <!-- トグルボタン-->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </header>

    <!-- メインコンテンツ-->
    <main>
        <!-- <main>タグの要素をすべて削除して以下に書き換え-->
        <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む-->
        {% block content %}{% endblock content %}
    </main>

    <!-- フッター -->
    <footer class="text-muted py-5">
        <div class="container">
            <p class="float-end mb-1">
                <a href="#">Back to top</a>
            </p>
            <!-- フッターのテキストを任意のものに書き換え-->
            <p class="mb-1">
                Product Gallery is &copy; Bootstrap, but please post a lot!</p>
        </div>
    </footer>

    <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</body>

</html>